#ifdef __ANDROID__
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class micwrapper_MicW */

#ifndef _Included_micwrapper_MicW
#define _Included_micwrapper_MicW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     micwrapper_MicW
 * Method:    Start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_micwrapper_MicW_Start
  (JNIEnv *, jclass, jint);

/*
 * Class:     micwrapper_MicW
 * Method:    Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_micwrapper_MicW_Stop
  (JNIEnv *, jclass);

/*
 * Class:     micwrapper_MicW
 * Method:    GetReadReady
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_micwrapper_MicW_GetReadReady
  (JNIEnv *, jclass);

/*
 * Class:     micwrapper_MicW
 * Method:    Read
 * Signature: ([FI)I
 */
JNIEXPORT jint JNICALL Java_micwrapper_MicW_Read
  (JNIEnv *, jclass, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
#endif // #ifdef __ANDROID__
